[package]
name = "bolos-sys"
version = "0.1.0"
authors = ["becominginsane <francesco@zondax.ch>"]
edition = "2018"

[dependencies]
cty = "0.2"

cfg-if = "1.0.0"

zeroize = { version = "1", default-features = false }

[dev-dependencies]
bolos = { version = "0.1", path = "../bolos" }
