[workspace]
members = ["app",
            "bolos", "bolos-derive",
            "zemu"]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
lto = false
codegen-units = 1
debug = true
opt-level = "s"
