name: Scheduled security audit
on:
  schedule:
    #run at hour 0 minute 0 every day of every month of every year
    - cron: '0 0 * * *'

defaults:
  run:
    working-directory: rust

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: cargo audit

      # disabled until we can change directory
      # see https://github.com/actions-rs/audit-check/issues/194
      # - name: Run audit
      #   uses: actions-rs/audit-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
